src/03- EndPoints/FrooshKar.EndPoints.MVC.UI/Areas/Admin/Controllers/HomeController.cs
using FrooshKar.Domain.Core.Contracts.ApplicationService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FrooshKar.EndPoints.MVC.UI.Areas.Admin.Controllers

{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {


        public async Task<IActionResult> Index()
        {
            return View();
        }

        


    }
}

src/03- EndPoints/FrooshKar.EndPoints.MVC.UI/Components/BidProductViewComponent.cs
using System.Runtime.InteropServices.ComTypes;
using FrooshKar.Domain.Core.Contracts.ApplicationService;
using Hangfire.Annotations;
using Microsoft.AspNetCore.Mvc;

namespace FrooshKar.EndPoints.MVC.UI.Components
{
	public class BidProductViewComponent : ViewComponent
	{

		private readonly IBidProductAppService _bidProductAppService;


		public BidProductViewComponent(IBidProductAppService bidProductAppService)
		{
			_bidProductAppService = bidProductAppService;
		}

		public async Task<IViewComponentResult> InvokeAsync(CancellationToken cancellationToken)
		{
			var getAllBidProducts = await _bidProductAppService.GetAll(cancellationToken);
			var notDeletedBidProducts = getAllBidProducts.Where(x => x.IsDeleted == false).ToList();
			var startedBidProducts =
				notDeletedBidProducts.Where(x => x.StartBidTime <= DateTime.Now && x.EndBidTime >= DateTime.Now)
					.ToList();
			return View(startedBidProducts);
		}
	}
}

src/03- EndPoints/FrooshKar.EndPoints.MVC.UI/Components/CategoryViewComponent.cs
using System.Threading;
using FrooshKar.Domain.Core.Contracts.ApplicationService;
using Microsoft.AspNetCore.Mvc;

namespace FrooshKar.EndPoints.MVC.UI.Components
{
	public class CategoryViewComponent : ViewComponent
	{
		private readonly ICategoryAppService _categoryAppService;

		public CategoryViewComponent(ICategoryAppService categoryAppService)
		{
			_categoryAppService = categoryAppService;
		}

		public async Task<IViewComponentResult> InvokeAsync(CancellationToken cancellationToken)
		{
			var getAllCategories = await _categoryAppService.GetAll(cancellationToken);
			var notDeletedCategories = getAllCategories.Where(x => x.IsDeleted == false).ToList();
			return View(notDeletedCategories);
		}
	}
}

src/03- EndPoints/FrooshKar.EndPoints.MVC.UI/Components/FixedPriceProductViewComponent.cs
using AutoMapper;
using FrooshKar.Domain.Core.Contracts.ApplicationService;
using FrooshKar.EndPoints.MVC.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace FrooshKar.EndPoints.MVC.UI.Components
{
    public class FixedPriceProductViewComponent:ViewComponent
    {
        private readonly IFixedPriceProductAppService _fixedPriceProductAppService;
        private readonly IMapper _mapper;

        public FixedPriceProductViewComponent(IFixedPriceProductAppService fixedPriceProductAppService, IMapper mapper)
        {
	        _fixedPriceProductAppService = fixedPriceProductAppService;
	        _mapper = mapper;
        }

        public async Task<IViewComponentResult> InvokeAsync(CancellationToken cancellationToken)
        {
            var getAllFixedPriceProducts = await _fixedPriceProductAppService.GetAll(cancellationToken);
            var notDeletedFixedPriceProducts = getAllFixedPriceProducts.Where(x => x.IsDeleted == false).ToList();
            return View(notDeletedFixedPriceProducts);
        }



	}
}

src/03- EndPoints/FrooshKar.EndPoints.MVC.UI/Components/VendorViewComponent.cs
using FrooshKar.Domain.Core.Contracts.ApplicationService;
using Microsoft.AspNetCore.Mvc;

namespace FrooshKar.EndPoints.MVC.UI.Components
{
	public class VendorViewComponent : ViewComponent
	{
		private readonly IVendorAppService _vendorAppService;

		public VendorViewComponent(IVendorAppService vendorAppService)
		{
			_vendorAppService = vendorAppService;
		}

		public async Task<IViewComponentResult> InvokeAsync(CancellationToken cancellationToken)
		{
			var getAllVendors = await _vendorAppService.GetAll(cancellationToken);
			var nonDeletedVendors = getAllVendors.Where(x => x.IsDeleted == false).ToList();
			return View(nonDeletedVendors);
		}

	}
}

src/03- EndPoints/FrooshKar.EndPoints.MVC.UI/Controllers/HomeController.cs
using System.Diagnostics;
using System.Runtime.CompilerServices;
using FrooshKar.Domain.Core.Contracts.ApplicationService;
using FrooshKar.EndPoints.MVC.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FrooshKar.EndPoints.MVC.UI.Controllers
{
    [AllowAnonymous]
	public class HomeController : Controller
	{

		public async Task<IActionResult> Index(CancellationToken cancellationToken)
		{
			return View();
		}



    }

}

src/03- EndPoints/FrooshKar.EndPoints.MVC.UI/Views/Home/Index.cshtml
@{
	Layout = "_Layout";

}

<section class="suggest-part">
	<div class="container">
		<div class="suggest-slider slider-arrow">
			@await Component.InvokeAsync("Category")
		</div>
	</div>
</section>




<section class="section feature-part">
	<div class="container">
		<div class="row">
			<div class="col-md-5 col-lg-5">
				<div class="section-side-heading">
					<h2>محصولات فروشندگان مختلف <span>تازه ها</span></h2>
					<p>
						تمامی کالاهای فروشندگان سراسر ایران را از سایت فروشکار تهیه کنید
					</p>
				</div>
			</div>

			<div class="col-md-7 col-lg-7">
				<div class="feature-item-slider slider-arrow">
					@await Component.InvokeAsync("FixedPriceProduct")
				</div>
				<div class="feature-thumb-slider"></div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="center-50">
					<a asp-controller="FixedPriceProduct" asp-action="ShowAllFixedPriceProduct" class="btn btn-inline"><i class="fas fa-eye"></i><span>مشاهده همه کالاهای قیمت مقطوع</span></a>
				</div>
			</div>
		</div>
	</div>
</section>





<section class="section recomend-part">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="section-center-heading">
					<h2>اینجا می تونی همه <span>غرفه داران رو ببینی! </span></h2>
					<p>
						هر غرفه داری که کالایی رو ثبت کرده از اینجا ببین
						کالای موردنظرت رو با بهترین قیمت ازش بخر!!
					</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="recomend-slider slider-arrow">
					@await Component.InvokeAsync("Vendor")
				</div>
			</div>
		</div>
	</div>
</section>


		
<section class="section recomend-part">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="section-center-heading">
					<h2>حتی می تونی <span>کالاهای مزایده ای بخری! </span></h2>
					<p>
						اینجا برای کالاهای مزایده ای قیمت ثبت کن
						اگه برنده شدی کالا مال تو می شه!!
					</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="recomend-slider slider-arrow">
					@await Component.InvokeAsync("BidProduct")
				</div>
			</div>
		</div>
	</div>
</section>