src/03- EndPoints/FrooshKar.EndPoints.MVC.UI/Controllers/FactorController.cs
using FrooshKar.Domain.Core.Contracts.ApplicationService;
using FrooshKar.Domain.Core.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FrooshKar.EndPoints.MVC.UI.Controllers
{
	[Authorize(Roles = "Customer")]
	public class FactorController : Controller
	{
		private readonly ICustomerAppService _customerAppService;
		private readonly IFactorAppService _factorAppService;
		private readonly ICommentAppService _commentAppService;

		public FactorController(ICustomerAppService customerAppService, IFactorAppService factorAppService, ICommentAppService commentAppService)
		{
			_customerAppService = customerAppService;
			_factorAppService = factorAppService;
			_commentAppService = commentAppService;
		}

		public async Task<IActionResult> Index(CancellationToken cancellationToken)
		{
			var currentCustomer = await _customerAppService.FindCurrentCustomerId(cancellationToken);
			var factors = await _factorAppService.GetAll(cancellationToken);
			var customerFactors = factors.Where(x => x.Carts.Any(c => c.CustomerId == currentCustomer) && x.IsDeleted == false).ToList();
			return View(customerFactors);
		}


		public async Task<IActionResult> ReleaseComment(int factorId, CancellationToken cancellationToken)
		{
			var model = new CommentDtoModel()
			{
				FactorId = factorId
			};
			return View(model);
		}
		[HttpPost]
		public async Task<IActionResult> ReleaseComment(CommentDtoModel model, CancellationToken cancellationToken)
		{
			await _commentAppService.Create(model, cancellationToken);
			return RedirectToAction("Index");
		}

		public async Task<IActionResult> ShowFactorsByDetail(int factorId, CancellationToken cancellationToken)
		{
			var currentCustomer = await _customerAppService.FindCurrentCustomerId(cancellationToken);
			var factors = await _factorAppService.GetAll(cancellationToken);
			var currentCustomerFinishedCarts = factors.Where(x => x.Carts.Any(c => c.CustomerId == currentCustomer) && x.IsDeleted == false).FirstOrDefault(y => y.Id == factorId).Carts;
			return View(currentCustomerFinishedCarts);
		}


	}
}

src/03- EndPoints/FrooshKar.EndPoints.MVC.UI/Views/Factor/Index.cshtml
@using Microsoft.AspNetCore.Razor.Language.Extensions
@using Microsoft.CodeAnalysis.Host
@using Microsoft.VisualStudio.Web.CodeGeneration.Templating
@model List<FrooshKar.Domain.Core.DTOs.FactorDtoModel>
@{
	Layout = "_Layout";
	int count = 1;
}
<div class="table-responsive">
	<table class="table table-bordered table-hover table-striped" id="data-table">

		<thead>
			<tr>
				<th>ردیف</th>
				<th>تاریخ ایجاد</th>
				<th>عملیات</th>
				<th>نظر شما</th>
			</tr>
		</thead>

		<tbody>

			@foreach (var item in Model)
			{
				<tr>
					<td>@(count++)</td>
					<td>@item.CreatedAt</td>
					<td>
						<a asp-controller="Factor" asp-action="ShowFactorsByDetail" asp-route-factorId="@item.Id" class="btn btn-info btn-round btn btn-primary">مشاهده جزئیات فاکتور</a>
					</td>
					<td>
						@if (item.Comment == null)
						{
							<a asp-controller="Factor" asp-action="ReleaseComment" asp-route-factorId="@item.Id" class="btn btn-info btn-round btn btn-primary">ثبت نظر</a>
						}
						else
						{
							<span>@item.Comment.Description</span>
						}
					</td>

				</tr>

			}

		</tbody>
	</table>
</div>

src/03- EndPoints/FrooshKar.EndPoints.MVC.UI/Views/Factor/ReleaseComment.cshtml
@model FrooshKar.Domain.Core.DTOs.CommentDtoModel
@{
	Layout = "_Layout";
}
<br/>
<form asp-controller="Factor" asp-action="ReleaseComment" method="post">
	<div class="container">
		<div class="form-group">
			<label>لطفا نظر خود را وارد نمایید:</label>
			<br/>
			<textarea asp-for="Description"></textarea>
			<input type="text" asp-for="FactorId" hidden/>
		</div>
		<button type="submit" class="btn btn-primary">ثبت نظر</button>
	</div>
</form>

src/03- EndPoints/FrooshKar.EndPoints.MVC.UI/Views/Factor/ShowFactorsByDetail.cshtml
@using Microsoft.AspNetCore.Razor.Language.Extensions
@using Microsoft.CodeAnalysis.Host
@using Microsoft.VisualStudio.Web.CodeGeneration.Templating
@model ICollection<FrooshKar.Domain.Core.Entities.Cart>
@{
	Layout = "_Layout";
	int count = 1;
}
<div class="table-responsive">
	<table class="table table-bordered table-hover table-striped" id="data-table">

		<thead>
		<tr>
			<th>ردیف</th>
			<th>نام کالا</th>
			<th>تعداد</th>
			<th>قیمت واحد</th>
			<th>عکس</th>

		</tr>
		</thead>

		<tbody>

		@foreach (var item in Model)
		{
			<tr>
				<td>@(count++)</td>
				<td>@item.FixedPriceProduct.Title</td>
				<td>@item.Count</td>
				<td>@item.FixedPriceProduct.UnitPrice</td>
				<td><img src="@item.FixedPriceProduct.ProductImages.FirstOrDefault().Url" style="width: 100px; height: auto"/></td>

			</tr>

		}

		</tbody>
	</table>
</div>